package cs62.rbeam.swingFinal;

import javax.swing.table.AbstractTableModel;
import cs62.rbeam.swingFinal.DataInterface.DataChangedEventListener;
import cs62.rbeam.swingFinal.DataInterface.DataEntry;

public class InventoryTableModel extends AbstractTableModel
{
	public InventoryTableModel(DataInterface data)
	{
		super();
		
		dataInterface = data;
		
		dataInterface.addDataChangedEventListener(new DataChangedEventListener() {
			@Override
			public void onDataChanged()
			{
				InventoryTableModel.this.fireTableDataChanged();
			}
		});
	}

	@Override
	public int getColumnCount()
	{
		return columnNames.length;
	}

	@Override
	public int getRowCount()
	{
		return dataInterface.getRowCount();
	}

	@Override
	public Object getValueAt(int rowIndex, int columnIndex)
	{
		DataEntry entry = dataInterface.getRow(rowIndex);
		
		switch (columnIndex)
		{
		case 0:
			if (entry.GenerateID)
			{
				return new String("Autogenerated");
			}
			return Integer.toString(entry.IDNumber);
		case 1:
			return Integer.toString(entry.Quantity);
		case 2:
			return entry.Name;
		case 3:
			return entry.Description;
		case 4:
			return "Click to view the image";
		default:
			return null;
		}
	}

	@Override
	public Class<?> getColumnClass(int columnIndex)
	{
		return Object.class;
	}

	@Override
	public String getColumnName(int columnIndex)
	{
		return columnNames[columnIndex];
	}

	@Override
	public boolean isCellEditable(int rowIndex, int columnIndex)
	{
		return true;
	}

	@Override
	public void setValueAt(Object value, int rowIndex, int columnIndex)
	{
		// We don't acutally need to do anything here
		// All of the work is done in the ItemEditDialog onSubmit handler
		/*
		DataEntry entry = dataInterface.getRow(rowIndex);
		
		switch (columnIndex)
		{
		case 0:
			entry.IDNumber = Integer.parseInt((String)(value));
		case 1:
			entry.Quantity = Integer.parseInt((String)(value));
		case 2:
			entry.Name = (String)(value);
		case 3:
			entry.Description = (String)(value);
		default:
		case 4:
			// This is done by the ItemEditDialog onFinished handler
			break;
		} // */
		
		fireTableCellUpdated(rowIndex, columnIndex);
	}
	
	private DataInterface dataInterface;
	
	static private String[] columnNames = {
		"ID #", "Quantity", "Name", "Description", "Image"
	};
}
